### ISSUE TITLE
Proxies.txt missing

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#11]
When running the project, proxies.txt gets loaded. This is not present. What should it be?

**Comment by zack6849** [comment]
Looks like it should be a list of HTTP proxies to pass through beautifulsoup
I presume this was deliberately left out, and you're meant to supply your own for testing or disable the proxy feature.

**Comment by cc-d** [comment]
Yes sorry.

Proxies.txt is simply an http proxy used with requests. This is used to prevent ip leakage when fetching titles/thumbnails.

Simply remove the portions of the requests.get calls which are called "proxies=proxies", and everything will work perfectly.

Site functionality will be identical without them, once the code related to them is removed.

**Comment by cc-d** [comment]
You may have a difficult time setting this up initially if you are not comfortable modifying the code. While it should be fairly easy to setup, most of my efforts today have been on active development over a focus on ease of deployment. This was supposed to be a pre-alpha, after all :)
