### ISSUE TITLE
Move the URL in the repo description to the website field

### ISSUE THREAD

**Issue by regner** [cc-d/ieddit#14]
If you put the URL in the actual website field it gets rendered as an actual link.

![image](https://user-images.githubusercontent.com/815037/65922533-76da5680-e39a-11e9-816b-64a3d4f605d6.png)

![image](https://user-images.githubusercontent.com/815037/65922504-5f9b6900-e39a-11e9-8c93-cb46edd89131.png)

**Comment by cc-d** [comment]
Awesome. I had forgone updating the title entirely, this looks much better.
