### ISSUE TITLE
Couple questions about contributions

### ISSUE THREAD

**Issue by regner** [cc-d/ieddit#16]
Looking to contribute a bit to the project and just had a few questions before jumping in:

First and foremost, is there anything specific you would like help on?

I was looking at starting with improving the general development experience. Setting up a Docker environment for local development for example. I was also wondering what your thoughts were on moving the python code into a folder `ieddit`? Would help clean up the root directory as more things get added for other purposes.

My thoughts on improvements for the dev experience:
* Setup docker compose and dockerfile
* Setup .editorconfig file (will match to what is currently being done)
* launch configs for VSCode to launch the python debugger and the application
* configure flake8 (depending how much it complains about)
* foundation work for tests, might not write anything but a basic test to start but just to get the framework there so more can be written easily, probably with pytest
* get flake8 and pytest running as github actions on every commit

Thoughts?

**Comment by lindsayemarc** [comment]
all these sound good to me :)

I'd recommend that you start with the docker local dev environment. We should wait and hear what @cc-d has to say

**Comment by cc-d** [comment]
I'm actually typing a reply right now. lol

**Comment by cc-d** [comment]
>First and foremost, is there anything specific you would like help on?

As of now, a captcha on the comment page would be extremely helpful. It should be fairly straight forward, and will be immediately useful. On the comment page, there are two comment reply input forms, one which appears under the post (which non-javascript users can use), and a another which is initially hidden but appends itself into a comment whenever a user clicks 'reply'.

General styling improvements are sorely needed. A large portion of the site is essentially pure white, pure black, and so on. The general layout is exactly what we should be going for, but the actual implementation of it can be dramatically improve.

Moving the code from the root directory is a good idea.  I probably should've did this from the start, but I had assumed this project would only be a few hundred lines max... lol. 

>Setup docker compose and dockerfile

Sure. I normally don't use docker, but I also am not normally writing code in collaboration with others, and certainly see it's benefits.

As to the coding style related tools, I'm open to them. I rushed this out extremely quickly so the code formatting in some places is a horror show. (which reminds me, a large amount of functionality like is_mod checks are essentially copy pasted, and should be moved to decorators at some point). To see a particularly horrific example of this, refer to the last lines in the main.js file related to autofilling and searching the sub suggestion dropdown. There is a LOT of room for code clean up.

>oundation work for tests, might not write anything but a basic test to start but just to get the framework there so more can be written easily, probably with pytest

Sounds great. Backend functions should be relatively easy to develop a testing routine for. I haven't used any form of github integration before, but it sounds interesting.

You seem to be far more familiar with these new and trendy technologies and standards than I am, I'll follow your lead as to what should be done in these areas.

**Comment by regner** [comment]
> I normally don't use docker, but I also am not normally writing code in collaboration with others, and certainly see it's benefits.

The nice thing about it is that it's there for those that need/want it but no requirement on using it.

> styling improvements

yeah... trust me you don't want me touching page styling :P

I will probably start with getting development environment working in docker, then look at captcha, then tests/linting/etc.

**Comment by cc-d** [comment]
Awesome. I sincerely appreciate the help.

**Comment by Pandawan** [comment]
Would love for a docker setup. I've been trying to set one up but am relatively new to it and must be doing something wrong in [my dockerfile](https://hastebin.com/oyekevocuk).

Once I get one setup, I'll try working on the styling.

EDIT: I've updated the dockerfile but still can't get the container to start from the image. It seems the postgres db isn't running.

**Comment by cc-d** [comment]
https://github.com/cc-d/ieddit/ - check out the updated README.md

I updated the install script and added an installation guide. These instructions worked for me on fresh a debian 9 vps.

If you have any issues let me know.

**Comment by Pandawan** [comment]
Awesome, I was able to get [a working Dockerfile](https://hastebin.com/wupaduvavo) by changing the URL and setting the database type to sqlite (for some reason, postgres wasn't working but sqlite seems fine).

Being somewhat inexperienced in docker, I have yet to find a way to allow for a "live-reloading" environment with Docker where the website's files can be directly edited without having to build another image. Maybe @regner has an idea?

**Comment by cc-d** [comment]
yeah, this is exactly why sqlite is set as the default db. glad you were able to get it working :)

**Comment by wnewlad** [comment]
@PandawanFr how are you working? vim or something directly in the vm? Or mounted on the host? Usually the live reload works by watching files/dirs for changes. If your working outside the vm, it might be an issue with cache or something that’s preventing the files from actually changing on the vm.

**Comment by Pandawan** [comment]
Okay, after some research, I got it to work. I have no idea if that's a best practice, but it's what I was able to gather from the [Docker docs on mounting](https://docs.docker.com/storage/bind-mounts/).

Here are [my changes that add Docker compatibility](https://github.com/PandawanFr/ieddit/commit/b572e0d2ede079d28faf3bc98b105097fab63219), should I make a PR or something? 

So a quick recap:
1. Build a docker image with `docker build --rm -f "Dockerfile" -t ieddit:latest .`
2. Run/Create container with `./docker_run.sh`, this mounts the `static` and `templates` folder in the container, allowing the editing of their files. 
    - Note: I didn't allow ALL files to be edited because python is already running/using the server's `.py` files so editing them would require restarting the container anyways. (I think right now, you need to build again when editing the py files).
    - If there's a better way to go about this, please tell me :)
3. Access website from `http://localhost:3000`

After that you can use the typical `docker stop ...` and `docker start ...` commands, etc.

**Comment by cc-d** [comment]
This should be included in #71
