### ISSUE TITLE
Self-text/Image expansion on posts.

### ISSUE THREAD

**Issue by cc-d** [cc-d/ieddit#17]
I'd like to implement functionality similar to RES where a use can click a + and expand images/text posts inline without having to visit the comment page of the post.

![image](https://user-images.githubusercontent.com/13108219/65926203-aba9d600-e3b9-11e9-85e0-c6c4d8e79525.png)

Similar to this. This is going to be my main priority for now.

Javascript users will not be able to use this, but it will enhance the site functionality for everybody else.

**Comment by wnewlad** [comment]
Done?

**Comment by cc-d** [comment]
indeed! good catch
