### ISSUE TITLE
Would a pull request for "dark mode" be accepted?

### ISSUE THREAD

**Issue by mini-eggs** [cc-d/ieddit#18]
Hello, Alice here. Been enjoying the site. Great job.

I'm interested in contributing and thought something I would make use of might be a good first step. Would a pull request for a "dark mode" or "dim/lights out mode" be accepted?

If I was giving free reign it would be implemented similarly to how my [personal site](https://evanjon.es/) has it. Relevant files being [here](https://github.com/mini-eggs/mini-eggs.github.io/blob/master/html/_scripts.html) and [here](https://github.com/mini-eggs/mini-eggs.github.io/blob/master/html/_footer.html). It's a minimal impl.

**Comment by cc-d** [comment]
Absolutely. I was actually going to prioritize working on this today.

[https://ieddit.com/r/imagine/293/imagine_browsing_this_bright-ass_website/](https://ieddit.com/r/imagine/293/imagine_browsing_this_bright-ass_website/)

I should have something up in a few hours, it will arrive in an update along side a user profile settings update.

**Comment by cc-d** [comment]
I'll push the user settings update first, if you'd like to implement the css, I'll only include the initial and give you free reign from there.

**Comment by cc-d** [comment]
I added the option, and the darkmode css is in static/darkmode.css

**Comment by mini-eggs** [comment]
Good stuff!
