### ISSUE TITLE
Cannot send messages

### ISSUE THREAD

**Issue by Eevoo** [cc-d/ieddit#19]
When I click a user profile page, there is the button for Send Messages. Currently...it does nothing.

**Comment by cc-d** [comment]
Could you elaborate? I just tested the button on a fresh account in incognito, and it seems to be working fine for me.

Are you logged in? If you are not logged in, you should get redirected to the /login page.

**Comment by Eevoo** [comment]
I am logged in, yes. Quick gifcam

![GIF](https://user-images.githubusercontent.com/49214133/65964481-1a734780-e42b-11e9-85a3-86dc939e2ceb.gif)

**Comment by Eevoo** [comment]
I am using Firefox ESR FWIW.

**Comment by cc-d** [comment]
```
<h6> user profile for {{ vuser.username }}</h6>
{% if session['username'] != vuser.username %}
<a href="/message/{{ vuser.username }}"><button type="button" class="btn btn-sm btn-outline-secondary">send message</a></button>
{% else %}
<a href="/u/{{ session['username'] }}/messages/"><button type="button" class="btn btn-sm btn-outline-secondary">view messages</a></button>
{% endif %}
```

So this is the code associated with that button on the user page. The link is being generated correctly, so I think this may have something to do with how your browser is treating the \<\/a\> tags inside of the button tags.

Try now.

**Comment by Eevoo** [comment]
No change in the UI. 

Message source is 


`<a href="/message/Lampshading"></a><button type="button" class="btn btn-sm btn-outline-secondary"><a href="/message/Lampshading">send message</a></button>`

And if I manually navigate to https://ieddit.com/message/Lampshading it shows the page.

**Comment by cc-d** [comment]
My bad, I had not yet restarted the server to reflect the updated code changes. Should be good now.

**Comment by Eevoo** [comment]
(Pre-restarted server workaround below)

![GIF](https://user-images.githubusercontent.com/49214133/65966504-34625980-e42e-11e9-8c18-c479bb91e7fa.gif)

Trying the new server now

**Comment by cc-d** [comment]
That button has gray text now with the updated code :)

If this ends up being the issue, I'll have to go through the codebase and ensure every button is formatted correctly.

**Comment by Eevoo** [comment]
It works! 

![GIF](https://user-images.githubusercontent.com/49214133/65966672-7095ba00-e42e-11e9-9929-39048b0d2bac.gif)

**Comment by cc-d** [comment]
:)

Thank you for your help.

**Comment by Eevoo** [comment]
Glad to be of service. ohwaitimean No thank you - you're the one who fixed it after all!
