### ISSUE TITLE
Requirements Version Pinning

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#22]
Via my PR at https://github.com/cc-d/ieddit/pull/21 -- It'd be good if these are pinned to a consistent version as well via `pip freeze` from the prod server.

**Comment by cc-d** [comment]
Absolutely. I'll get an updated list.

**Comment by cc-d** [comment]
https://github.com/cc-d/ieddit/commit/4193817a9036b2fe6f2f1cfee3ea50f2c9483ec4

pip3 freeze results

**Comment by stets** [comment]
@cc-d  I think many of these are unnecessary. 
I assumed you were running from a virtual environment, which I believe would only show the python modules required to run the app. 
Many of these will not work in a mac environment, namely:

- unattended-upgrades==0.1
- distro-info
- python-apt

**Comment by cc-d** [comment]
See: https://github.com/cc-d/ieddit/pull/24

Necessary packages involving captcha and rate limiting were omitted.

**Comment by stets** [comment]
added psycopg2 to master -- closing this
