### ISSUE TITLE
Local Dev Environment Consistency

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#23]
I'd love to contribute to this project but there is little documentation on how to spin up the project locally. Adding this info to the Readme would help out a lot!

**Comment by cc-d** [comment]
For sure. Currently deployment can be a little tenuous, you actually have to modify a session library depending on what form of session caching you use.

**Comment by cc-d** [comment]
There are a few packages missing as well, that https://github.com/PandawanFr mentioned https://hastebin.com/oyekevocuk here.

**Comment by cc-d** [comment]
https://github.com/cc-d/ieddit/ - check out the updated README.md

I updated the install script and added an installation guide. These instructions worked for me on fresh a debian 9 vps.

If you have any issues let me know.

**Comment by cc-d** [comment]
turns out im just silly and mr. sets was on point all along

**Comment by stets** [comment]
I'd suggest re-opening this....Readme needs a lot of work for folks wanting to spin up a dev env @cc-d 

happy to help there
