### ISSUE TITLE
Dockerize Ieddit

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#25]
Getting a dev environment should be as simple as `docker-compose up` for those who work with docker. (I'm open to work on this one unless someone beats me to it )

Working on this in a branch at 
~~https://github.com/stets/ieddit/tree/dockerize~~
edit:
Pulled my fork branch into master branch `dockerize` here:

https://github.com/cc-d/ieddit/tree/dockerize

Running into lots of issues with imports...this will have to be dealt with before the docker branch

**Comment by Pandawan** [comment]
Hey, I've gotten Docker to work with this repo as mentioned [in this other issue](https://github.com/cc-d/ieddit/issues/16#issuecomment-540300335). 

I'm kind of new to Docker so I don't know if it's the best way to go about it. If you think it's fine, I'll submit a PR.

**Comment by stets** [comment]
@PandawanFr  go ahead -- I can review and we can collab on it. 
I ran into a few issues but maybe your PR will have some solutions :-)

**Comment by burntcarrot** [comment]
@stets Since @PandawanFr seems to have fixed this issue and the PR has been merged into the **dockerize** branch, so maybe this issue can be closed of as now, as we don't require help anymore.

**Comment by cc-d** [comment]
will do
