### ISSUE TITLE
Project issues when running on Mac 

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#26]
There are many `os.system` calls that assume a user is running debian. These should be changed to run on any system.

https://github.com/cc-d/ieddit/blob/91216b1034f16dbbbe86fb7746a918343dff0f2c/create_db.py#L18

**Comment by cc-d** [comment]
```ieddit-dev:~/ieddit# grep -rsi "os.system" .
./ieddit.py:                    #os.system('python3 get_thumbnail.py %s "%s"' % (str(new_post.id), urllib.parse.quote(url)))
./ieddit.py:                    _thread.start_new_thread(os.system, ('python3 get_thumbnail.py %s "%s"' % (str(new_post.id), urllib.parse.quote(url)),))
./create_db.py:#os.system('rm -rf test.db')
./create_db.py:    os.system('bash recreate_psql_db.sh')
```

Here are the four places os.system is called. Achieving cross-system compatibility should be fairly easy. These calls can even be omitted completely, and nothing would be lost except the psql db script automatically running and thumbnails.

**Comment by wnewlad** [comment]
worked fine on mac today.. close?

**Comment by cc-d** [comment]
glad to hear. i'll tentatively close this for now
