### ISSUE TITLE
test.db deleted when sqlite used

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#30]
Why does the `username`.db get deleted here?

https://github.com/cc-d/ieddit/blob/58b9aa48d9f506a62acefc57ae6eeb210312d67a/create_db.py#L34

**Comment by cc-d** [comment]
So any changes to the schema in models.py are reflected in a fresh database.
'test' was the username, and the db before was 'test'.db, so I decided just to re-use that variable. 

this way you do not have to bother with updating columns, a recreated database has the correct schema from the start.

**Comment by stets** [comment]
> So any changes to the schema in models.py are reflected in a fresh database.
> 'test' was the username, and the db before was 'test'.db, so I decided just to re-use that variable.
> 
> this way you do not have to bother with updating columns, a recreated database has the correct schema from the start.

Anyone running this from scratch will hit an exception because the db file does not exist

**Comment by cc-d** [comment]
bah. you're right.

i was used to the old os.system call which would fail silently

kind of an obvious oversight

**Comment by cc-d** [comment]
https://github.com/cc-d/ieddit/commit/fec4d608b4559c36e28165fe37d572e52b15f4cc

fixed here
