### ISSUE TITLE
Consider Implementing Sentry.io

### ISSUE THREAD

**Issue by stets** [cc-d/ieddit#34]
Sentry.io is awesome -- you can catch errors that you're users are having without scrubbing through logs or setting something else up

**Comment by cc-d** [comment]
This seems like a really cool product. If/when the userbase any appreciable size, I'd certainly love having something like this.

**Comment by stets** [comment]
It's free until you're doing a boatload of events. Super simple to implement too, so you can get value from it today. @cc-d

**Comment by cc-d** [comment]
cool, i'll look into it

**Comment by stets** [comment]
support added in https://github.com/cc-d/ieddit/pull/39

up to @cc-d  if he wants to add it to his operations  :-)

**Comment by cc-d** [comment]
even if i don't personally use it, having the option is only a positive for anybody who wants to use it on their own ieddit instance.

right now scale is small enough to where a local error log is more than adequate for helping me identify any issues, but if/when ieddit scales to a decent level of traffic (and i verify it won't compromise user privacy in any way), i'll enable this on the prod server.
