### ISSUE TITLE
Captcha failures causes rate limits

### ISSUE THREAD

**Issue by myfirstnameispaul** [cc-d/ieddit#45]
I'm not sure if this is intentional, but rate limits kick in after failing a bunch of captchas, then trying to leave a comment gives a message that I'm rate limited. IIRC, this happens after trying to leave the comment and the comment text is vaporized.

It happens with just normal use.

**Comment by cc-d** [comment]
So, the way the rate limiting timer works is by calling set_rate_limit() after post/comment/etc creation.

You shouldn't ever see the fail limit message when a captcha is failed, only completed. 

Comments did not have captchas attached to them until literally 40 minutes ago so it was very easy to accidentally trigger the rate limit by double posting.

The rate limit also transfers across different events. For example, if the rate limit is set to 20 seconds, you will have to wait 20 seconds after creating a subreddit to create a new post/comment.

I'm tentatively closing this for now, tell me if you encounter this in the future.
