### ISSUE TITLE
Imagine not being able to login and not having a way to report the issue

### ISSUE THREAD

**Issue by nomorepanic** [cc-d/ieddit#48]
> Imagine not being able to login and not having a way to report the issue

Unless you're on github. 

The login form is broken as of now.

**Comment by jomawi** [comment]
I tried logging in, and now it says 500 internal server error.

**Comment by cc-d** [comment]
Should be resolved!

Sorry about this! Details as to why this happened, and how this happened, can be found here:
https://ieddit.com/i/ieddit/699/why_the_site_was_down_aka_textageddon/
