### ISSUE TITLE
cross-site scripting vulnerability

### ISSUE THREAD

**Issue by eidyz** [cc-d/ieddit#59]
Hi.
The sub's description textarea doesn't get sanitized which results in pretty easy xss target.
My payload was simply `<sVg oNloaD="alert``"/>`
I don't know much about python so I am not going to be able to make a PR but I thought I'd let you know at least.

**Comment by cc-d** [comment]
https://github.com/civicsoft/ieddit/commit/406549b6904a67ab9dd556bfa497de128157bec9

taken care of with this. the pseudo markup function does a few unique things, so it's used here in stead.

THANK YOU for looking for this.

**Comment by eidyz** [comment]
@cc-d  It is also possible to inject xss payloads when sending messages to other users

**Comment by cc-d** [comment]
thanks. i'll patch that immediately

**Comment by cc-d** [comment]
https://github.com/civicsoft/ieddit/commit/eeb41315d82cfa51d3db48c772d4cd5465be7925

While looking at messages for the xss you mentioned, I found another place where it was possible as well.  You could send a post request to /message with the encrypted flag set, with any text you want, and it would be rendered as |safe without escaping.

Both should be patched here.
