### ISSUE TITLE
Comment not shown as "edited" after making changes.

### ISSUE THREAD

**Issue by burntcarrot** [cc-d/ieddit#74]
![ieddit-edited](https://user-images.githubusercontent.com/53528139/67516161-c5d78b00-f6bd-11e9-8974-64315eecafcd.png)

After editing a comment, it should be shown as `edited` in the top panel. I think this should be fixed as earlier as possible.

**Comment by cc-d** [comment]
Sure. Right now comments don't have that property, but they definitely should.

**Comment by cc-d** [comment]
![image](https://user-images.githubusercontent.com/13108219/67540998-011d8e00-f6ad-11e9-8b92-6b3e5f7be1d8.png)
It seems to be working here. I'll see if I can reproduce this.

**Comment by cc-d** [comment]
Oh, I think you are suggesting it be changed entirely, not commenting on it not showing up properly.

There is no plan to further distinguish comments as edited. The marker is meant to be inoffensive and subtle.

**Comment by burntcarrot** [comment]
@cc-d You might want to see users' opinions on this: [Ieddit Thread](https://ieddit.com/i/ieddit/4088/major_feature_request3A_comments_and_po/)

**Comment by cc-d** [comment]
Yeah I read that thread recently.

The 'show last edited time' on mouseover I like, but the indicator showing that a post has been edited will not become much more visible than it already is. It's something that only a minimum amount of attention should be drawn to, and exists mainly to provide context in the case that somebody edits their post/comment to be something completely different.
