### ISSUE TITLE
Weird spacing bug using Markdown in comments.

### ISSUE THREAD

**Issue by burntcarrot** [cc-d/ieddit#75]
![ieddit-spacing-bug](https://user-images.githubusercontent.com/53528139/67516291-0afbbd00-f6be-11e9-98c7-17213e3e60ab.png)

Text posts seem to be glitchy after using Markdown in the comments. `self` in the image seems to have shifted some spaces from the original text.

**Comment by cc-d** [comment]
Yeah, there is a TON of markdown weirdness present at the moment. That is probably due to it being in [code] tags, which have been styled primarily for the larger ``` multi-line codeblocks. It will be fixed.

**Comment by cc-d** [comment]
complete rewrote pseudo_markup here https://github.com/civicsoft/ieddit/commit/b88c06082859802f5c0e17337226533d29f9b74a

thing was a goddamn abomination before, i am glad to be rid of it.
