### ISSUE TITLE
Blocking has issues

### ISSUE THREAD

**Issue by myfirstnameispaul** [cc-d/ieddit#81]
When I block a user the user is still able to comment on my posts and comments, and I even receive notifications to such.

Is this the expected behavior?

**Comment by cc-d** [comment]
so, the user will still be able to comment on your posts/comments, but you should not see them or anybody who replies to them.

you also shouldn't receive messages from somebody you blocked, until you unblock them anyway.

i'll look into this when i get done with what i'm working on currently

**Comment by myfirstnameispaul** [comment]
> the user will still be able to comment on your posts/comments, but you should not see them or anybody who replies to them.

I don't find this a desirable behavior. If there is something being discussed, especially in my post, that I don't approve of, then I don't want it there. Keeping this behavior is highly discouraging.

**Comment by cc-d** [comment]
https://github.com/civicsoft/ieddit/commit/3b14ef2e2e4d90fa939f8390aa770b3422e89f51 blocking seems to be working correctly as of this commit.
