### ISSUE TITLE
Perpetual unread message icon

### ISSUE THREAD

**Issue by myfirstnameispaul** [cc-d/ieddit#83]
The unread message icon is nearly always showing 1 unread message, even when I have no unread messages.

Strangely, it sometimes goes away, then comes back. I really can't find any consistent way to repeat this, so I can't communicate further. However, I am going to suggest it has something to do with blocking a commenter that left a comment after being blocked.

**Comment by burntcarrot** [comment]
@cc-d I seem to face the same issue. The notifications seem to be inconsistent. When I refresh the page, the unread messages resets to zero. We need to look into this consistent behaviour.

**Comment by wnewlad** [comment]
Has anyone else seen voting button oddities too? Not sure how/if related if it might be session or profile related, but especially on the “comments” page in a sub, there will be comments that aren’t reflecting vote status correctly. I.e. the upvote arrow won’t be orange despite having previously voted. Then when trying to upvote, nothing appears to happen. There was a short period in one release where the text would appear (“already voted” or something like that) but it seems to be missing now and it just seems broken with no feedback or change of arrow color.

**Comment by cc-d** [comment]
this was realted to the session fuckery i'm fairly sure.
