### ISSUE TITLE
Vote arrows not reflecting votes

### ISSUE THREAD

**Issue by wnewlad** [cc-d/ieddit#85]
Not sure if it might be session or profile related, but especially on the “comments” page in a sub, there will be comments that aren’t reflecting vote status correctly. I.e. the upvote arrow won’t be orange despite having previously voted. Then when trying to upvote, nothing appears to happen. There was a short period in one release where the text would appear (“already voted” or something like that) but it seems to be missing now and it just seems broken with no feedback or change of arrow color.
![D85C6C1D-3C94-4E39-BE91-C415C6DC07BE](https://user-images.githubusercontent.com/56266673/67637101-8a031800-f8ad-11e9-992d-823d46b72f16.png)
![5874A8A7-939B-431E-844B-5336CA506057](https://user-images.githubusercontent.com/56266673/67637102-8a031800-f8ad-11e9-92b9-a3ec6a55ecd6.png)
![1C38F1E4-2E88-4DC9-844E-12804074A09C](https://user-images.githubusercontent.com/56266673/67637103-8a031800-f8ad-11e9-9eb5-6c27020c75eb.png)

**Comment by dtaivpp** [comment]
@wnewlad this may be related to another bug we are experiencing on the backend. We can take a look at it. I have noticed it, especially regarding downvotes in my case.

**Comment by wnewlad** [comment]
@dtaivpp which bug?

**Comment by dtaivpp** [comment]
@wnewlad I don't think we have an issue open for it, but you can see it in the Error discord channel.

**Comment by cc-d** [comment]
the post votes are fixed, this should be fixed as well
