### ISSUE TITLE
Image issues (possible hotlink protection?)

### ISSUE THREAD

**Issue by wnewlad** [cc-d/ieddit#86]
Some images seem to be broken. 

![17A3E033-5D2D-43A0-8947-28C108122B19](https://user-images.githubusercontent.com/56266673/67637508-b7ea5b80-f8b1-11e9-9dad-be98a5832b09.png)

The direct link to the image (https://c10.patreonusercontent.com/3/eyJ3IjoxOTIwfQ%3D%3D/patreon-media/p/campaign/3376319/0ae9401167224efaab36ba53aff0ca4c/2.jpg?token-time=1572393600&amp;token-hash=k_hNg5Oz2FR4EmNM_SDE0XlDXzGUD2IG6eQlbWnVCV8%3D) doesn’t seem to work at all (with or without token) but it’s fine on the original page. Might be some kind of hotlink protection.

**Comment by cc-d** [comment]
seems like it
