### ISSUE TITLE
Numbered lists in text posts breaking

### ISSUE THREAD

**Issue by dtaivpp** [cc-d/ieddit#89]
I added a numbered list into my post's text body and it got formatted to all '1.' items. 

Input:
1. 
2. 
3. 

Output:
![image](https://user-images.githubusercontent.com/17506770/67679289-246f6400-f95f-11e9-85cf-7e31403f2c3f.png)

**Comment by cc-d** [comment]
complete rewrote pseudo_markup here https://github.com/civicsoft/ieddit/commit/b88c06082859802f5c0e17337226533d29f9b74a

thing was a goddamn abomination before, i am glad to be rid of it.
